/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/editor.vue')['default']
    ElementWithLine: typeof import('./src/components/elementWithLine.vue')['default']
    Input1: typeof import('./src/components/input1.vue')['default']
    ListApp: typeof import('./src/components/listApp.vue')['default']
    MainInput: typeof import('./src/components/mainInput.vue')['default']
    MultipleEditors: typeof import('./src/components/multipleEditors.vue')['default']
    SvgEdit: typeof import('./src/components/svgEdit.vue')['default']
    TaskElement: typeof import('./src/components/taskElement.vue')['default']
    TopBar: typeof import('./src/components/topBar.vue')['default']
  }
}
